Baptiste nusaibah validation
Oncostat/grstat pull request #11
Opened 2024-09-23 14:32 UTC by BaptisteArchambaud

Add of functions for validation of function ae_table_grade

2024-09-23 15:12 UTC, DanChaltiel requested changes
Très bon début c'est super !

Il faut qu'on discute de l'output.
A terme, il faut que ça ait la structure d'un test de package, donc avec la syntaxe de testthat que je vous avais présentée.
https://github.com/Oncostat/grstat/blob/main/tests/testthat/test-ae-tables.R
Cette syntaxe n'a pas de nuance, soit le test passe, soit il échoue.

Proposition :
* utiliser `expect_xxx()` pour tester les différences de N et pct (diff majeure)
* utiliser `message()` pour signaler les différences de style (diff mineure), genre les informations manquantes dans une tables mais pas dans l'autre

Par contre c'est difficile de lire le code sans voir l'application vu que les data sont private.
Ce serait compliqué de faire ce qu'il y a dans https://github.com/Oncostat/grstat/issues/9 pour pouvoir tout faire sur GitHub ?

2024-09-23 15:23 UTC, BaptisteArchambaud commented on R/validation fonctions AE_table_grade/group_grades_zeroNA.R
> +    distinct(grade, .keep_all = T) %>%
je crois que c'est parce que je n'arrivais pas à keep toutes les variables dans la base avec summarize(.by=) quand il y avait plusieurs bras

2024-11-12 14:55 UTC, DanChaltiel commented on R/utils_outputs_ae_table_grade.R
> +    )
Belle utilisation de `imap()` :-)
Il y a une nouvelle fonction de`tidyr` qui fera le taff aussi : 
```r
data %>% 
  separate_wider_regex(cols=-c(.id, label, variable, grade), 
                       patterns=c(N="\\d+", " \\(", pct="\\d+", "%\\)"))
```

2025-04-07 09:30 UTC, DanChaltiel reviewed
Super Nusaibah, merci beaucoup !
Par contre il y a des erreurs dans les outputs donc ce n'est malheureusement pas terminé 😕.
Désolé de t'embêter encore !

Pour simplifier le process, je t'ai créé un dossier `\rsas\_test_nusaibah\` avec tous les inputs/outputs/tests standardisés. Tu peux lancer le rproj et sourcer (ctrl shift s) le fichier `test.nusaibah.R` directement.
Le dossier `fonctions_validationR` contient tes fonctions de validations sans modification de ma part (je crois, en tout cas pas dans `compare_xxx`, mais remplace par tes propres fichiers pour être sûr). 
Tu peux modifier ce que tu veux comme bon te semble, je n'y touche plus.

La fonction `add_errors()` ajoute une erreur standard à la 2ème ligne des tableaux R. Ca devrait correspondre au grade 1 dans AEGRADE, mais l'output donne le grade 0 pour les pourcentages.
Dans AESOC, il y a un problème de jointure quand on renseigne les termes and plus des SOC, je t'ai mis la ligne en code-review.

Je reste évidemment dispo si besoin qu'on en discute :-) !

2026-07-15 08:02 UTC, closed without merging